# Replace the text below to customize your site
site_name: Kecheng Zhang Fab Academy Site
site_description: My Fabacademy site

site_author: Kecheng Zhang
docs_dir: _docs
site_dir: docs
copyright: Creative Commons Attribution Non Commercial
theme:
  name: material
  # see https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Swith to dark mode
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: "lime"
    accent: "indigo"
  font:
    false
    # text: "Ubuntu"
    # code: "Ubuntu Mono"
feature:
    - navigation.tabs
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/academany"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/in/kecheng-zhang-5023b255/"

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
